version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'ejemplo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  almacen:
    image: ejemplo-almacen:latest
    build: .
    restart: always
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_DATABASE: 'ejemplo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
    ports:
      - "8080:8080"

volumes:
  mysql:
